# Buildpack API version
api = "{{.BuildpackApi}}"

# Buildpack ID and metadata
[buildpack]
  id = "{{.BuildpackID}}"
  version = "{{.BuildpackVersion}}"

# Stacks that the buildpack will work with
[[stacks]]
  id = "{{.BuildpackStacks}}"